spring:
  application:
    name: lms

  datasource:
    url: jdbc:postgresql://localhost:5432/university
    username: avazkhon
    password: 1234
  data:
    redis:
      host: localhost # default
      port: 6378 # default
#      password: if needed

  jpa:
    hibernate:
      ddl-auto: update


    properties:
      hibernate:
        format_sql: false
        show_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  defaultValues:
    host: http://app.avazkhon.uz

#  profiles:
#    active: dev

  sql:
    init:
      mode: never

infobip:
  api:
    url: "https://9k1844.api.infobip.com/sms/2/text/advanced"
    key: "803ec566e8ae96734162759372aa2084-03461112-9598-456e-bd5f-0b1d6a4bcf62"


logging:
  level:
    uz.mu.lms: TRACE

server:
  address: 0.0.0.0
  port: 8080


